### ISSUE TITLE
text selection 

### ISSUE THREAD

**Issue by borian** [nwtgck/gh-card#7]
If `<embed>` is used instead of `<img>` the text inside the gh-card is selectable.

`<embed src="https://gh-card.dev/repos/mozilla/send.svg?fullname" />`

**Comment by nwtgck** [comment]
@borian Thanks. I didn't know browsers make an SVG in `<embed>` selectable. I'll work on it.

**Comment by nwtgck** [comment]
@borian I'm working on it. I found `<a href='...'><embed src="...svg"></a>` can not be clicked. So, that  means I should do #4 first.

**Comment by nwtgck** [comment]
@borian 

I found an issue. Combination of `<embed>` and `links` in SVG are not good because we can't jump to the links. Here is a simple demo on Codepen.

![gh-card-issue-7 mp4 opt](https://user-images.githubusercontent.com/10933561/59546435-67104100-8f68-11e9-92fb-5166151745ba.gif)
Codepen: <https://codepen.io/nwtgck/pen/vqLeJW>

**Comment by trishmapow** [comment]
Googled around for 5 minutes, just need to change `href` to `xlink:href` and and `target=_blank`.

Codepen: https://codepen.io/anon/pen/RzrjZd
Source: https://alligator.io/svg/hyperlinks-svg/

**Comment by MaxBittker** [comment]
great research ya'll :)

**Comment by kena0ki** [comment]
The link problem seem to be happen due to Content-Security-Policy.
We can avoid this by adding target attribute as @trishmapow mentioned it.
The value of target attribute can be  _parent or _top in addition to _blank though.

**Comment by nwtgck** [comment]
Thank you very much for all. This was solved in #104 by @kena0ki.
